Traceback (most recent call last):
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/skojaku-admin/miniforge3/envs/applsoftcomp/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pval = stats.kstest(numbers, stats.uniform(loc=0.0, scale=max(numbers)).cdf)[1]
test_result = "The numbers are uniform distributed" if pval > 0.05 else "The numbers are not uniform distributed"
message = mo.callout(test_result, color = "red" if pval <= 0.05 else "green")
message
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m pval [38;5;241m=[39m stats[38;5;241m.[39mkstest(numbers, stats[38;5;241m.[39muniform(loc[38;5;241m=[39m[38;5;241m0.0[39m, scale[38;5;241m=[39m[38;5;28mmax[39m(numbers))[38;5;241m.[39mcdf)[[38;5;241m1[39m]
[1;32m      2[0m test_result [38;5;241m=[39m [38;5;124m"[39m[38;5;124mThe numbers are uniform distributed[39m[38;5;124m"[39m [38;5;28;01mif[39;00m pval [38;5;241m>[39m [38;5;241m0.05[39m [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124mThe numbers are not uniform distributed[39m[38;5;124m"[39m
[0;32m----> 3[0m message [38;5;241m=[39m [43mmo[49m[38;5;241;43m.[39;49m[43mcallout[49m[43m([49m[43mtest_result[49m[43m,[49m[43m [49m[43mcolor[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mred[39;49m[38;5;124;43m"[39;49m[43m [49m[38;5;28;43;01mif[39;49;00m[43m [49m[43mpval[49m[43m [49m[38;5;241;43m<[39;49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m0.05[39;49m[43m [49m[38;5;28;43;01melse[39;49;00m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mgreen[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      4[0m message

[0;31mTypeError[0m: callout() got an unexpected keyword argument 'color'

